# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Part-time job' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Part-time job

pod 'Firebase/Analytics'
pod 'Firebase/Auth'	
pod 'Firebase/Core'
pod 'Firebase/Firestore'

end
